### ISSUE TITLE
Summarizer.py error in semantic kernal module

### ISSUE THREAD

**Issue by colincole** [mario-guerra/azure-openai-doc-summarizer#7]
This happens when I run it:

python summarizer.py sample-narrative.docx out.docx

Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\GitHub\azure-openai-doc-summarizer\summarizer.py", line 31, in <module>
    from semantic_kernel.connectors.ai.chat_request_settings import ChatRequestSettings
ModuleNotFoundError: No module named 'semantic_kernel.connectors.ai.chat_request_settings'

**Comment by mario-guerra** [comment]
Thank for reporting this! Fixed with https://github.com/mario-guerra/azure-openai-doc-summarizer/pull/8, removing semantic kernel completely.
